name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches: 
      - master

jobs:
  job1:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: view the github context
        shell: bash
        run: |
          echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
          echo "github.workspace = ${{ github.workspace }}"
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Checkout
        uses: actions/checkout@v2.3.2

      - name: set message
        run: |
          merge_commit_title="Merge pull request #${{ github.event.pull_request.number }} from ${{ github.event.pull_request.head.label }}"
          merge_commit_message="${{ github.event.pull_request.title }}"
          
          echo "merge_commit_title = $merge_commit_title"
          echo "merge_commit_message = $merge_commit_message"

  job2:
    needs: [job1]
    if: ${{ github.event.action == 'labeled' && github.event.label.name == 'automerge' }}
    name: Automatically merge PR
    runs-on: ubuntu-latest
    steps:
      - name: auto-merge PR
        uses: juliangruber/merge-pull-request-action@v1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.pull_request.number }}
