name: Pull Request

on:
  pull_request:
    branches: 
      - master

jobs:
  job1:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: view the github context
        shell: bash
        run: |
          echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
          echo "github.workspace = ${{ github.workspace }}"
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Checkout
        uses: actions/checkout@v2.3.2

  job2:
    needs: [job1]
    name: Automatically merge PR
    runs-on: ubuntu-latest
    steps:
      - name: auto-merge PR
        uses: pascalgn/automerge-action@v0.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
