name: Pull Request

on: pull_request

jobs:
  job1:
    runs-on: [self-hosted, Win10VS2019-01]
    steps:
      - name: view the github context
        shell: bash
        run: |
          echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
          echo "github.workspace = ${{ github.workspace }}"
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

#       - name: Checkout
#         uses: actions/checkout@v2.3.2

  job2:
    runs-on: [self-hosted, Win10VS2019-01]
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: ${{ github.ref }}
          clean: true
          lfs: true

      - name: view the github context
        shell: bash
        run: |
          echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
          echo "github.workspace = ${{ github.workspace }}"
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
