name: Pull Request

on: [pull_request, pull_request_review, pull_request_review_comment, pull_request_target]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: view the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
