name: Pull Request

on:
  pull_request_review_comment:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: view the github context
        shell: bash
        run: |
          echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
          echo "github.workspace = ${{ github.workspace }}"
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

#       - name: Checkout
#         uses: actions/checkout@v2.3.2
