name: Pull Request

on: [pull_request, pull_request_review, pull_request_review_comment, pull_request_target]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: view the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Create a check run
        if: github.event_name == 'pull_request'
        run: |
          curl \
          -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.antiope-preview+json" \
          https://api.github.com/repos/${{ github.repository }}/check-runs \
          -d '{
           "name": "code-coverage",
           "head_sha": "${{ github.sha }}",
           "status": "completed",
           "conclusion": "failure",
           "output": {
             "title": "code-coverage report"
             "summary": "See here."
           }
          }'
