name: Pull Request

on: [pull_request]

jobs:
  job1:
    runs-on: [self-hosted, Win10VS2019-01]
    steps:
      - name: view the github context
        shell: bash
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Checkout
        uses: actions/checkout@v2.3.2

      - name: Print env
        shell: bash
        run: printenv

  job2:
    runs-on: [self-hosted, Win10VS2019-02]
    steps:
      - name: view the github context
        shell: bash
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Checkout
        uses: actions/checkout@v2.3.2

      - name: Print env
        shell: bash
        run: printenv
