name: Pull Request

on: [pull_request, pull_request_review, pull_request_review_comment, pull_request_target]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: view the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Add team reviewers
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          curl \
          -X POST \
          -H "Authorization: token ${{ secrets.REPO_SCOPE }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers \
          -d '{"team_reviewers":["TestWorkflowsRML/allme"]}'
