name: Pull Request

on: [pull_request, pull_request_review, pull_request_review_comment, pull_request_target]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: view the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Upload coverage reports
        uses: codecov/codecov-action@v1.0.13
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          files: ./coverage1.xml,./coverage2.xml
          flags: unittests
          name: my-codecov-report
          fail_ci_if_error: true
