name: Test Manual Trigger

on:
  workflow_dispatch:
  push:
    paths: 
      -  '**'
      - '!Readme.md'
      - '!.github/**'
      - '.github/workflows/Test-Manual-Trigger.yml'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: view the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: sleep
        run: |
          echo "START: $(date +"%H:%M:%S")"
          sleep 2m 20s
          echo "END: $(date +"%H:%M:%S")"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: view the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: wait job1 completed
        shell: bash
        run: |
          status=""
          conclusion=""
          while [ "$status" != "completed" ]
          do
            response=$(curl --request GET \
            --url 'https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs' \
            --header 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
            --header 'Accept: application/vnd.github.v3+json')
            
            echo "--------------------------------------------------------------------------------------------------"
            echo "$response"
            echo "--------------------------------------------------------------------------------------------------"
            
            status=$(echo $response | jq -r '.jobs[] | select(.name=="job1" | .status)')
            echo $status
            if [[ $status == completed ]]; then
              conclusion=$(echo $response | jq -r '.jobs[] | select(.name=="job1" | .conclusion)')
              echo $conclusion
            fi
          done
          
          if [[ $conclusion == success]]; then
            echo "job1 has completed successfully."
          else
            echo "job1 has completed but $conclusion."
          fi
