name: Test Manual Trigger

on:
  workflow_dispatch:
    inputs:
      msg:
        description: 'Message to show in log'
        default: 'This workflow run is triggered by manual.'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: view the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: run action
        uses: ActionsRML/Test-JavaScript-action@master

      - name: view envs
        run: printenv

      - name: print input msg
        run: echo "${{ github.event.inputs.msg }}"
