name: Test Manual Trigger

on:
  workflow_dispatch:
    inputs:
      msg:
        description: 'Message to show'
        default: 'yes'

env:
  INPUT_MSG: ${{ github.event.inputs.msg }}

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: view the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: print input msg
        if: |
          github.event.inputs.msg == 'yes' ||
          github.event.inputs.msg == 'true'
        run: |
          echo "msg = ${{ github.event.inputs.msg }}"
          echo "INPUT_MSG = $INPUT_MSG"
