name: Test Manual Trigger

on:
  push:
    paths: 
      -  '**'
      - '!Readme.md'
      - '!.github/**'
      - '.github/workflows/Test-Manual-Trigger.yml'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: view the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
